### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by eserte** [ManocLabs/manoc#198]
On some of my smoker systems I see test failures:
```
#   Failed test 'Text contains "Address field is required"'
#   at t/controller/device.t line 34.
#     searched: "Manoc - New deviceToggle navigation   Manoc 3   Us"...
#   can't find: "Address field is required"
#         LCSS: "Address "
# LCSS context: "ange passwordLogout   Network  Devices IP Address "
# Looks like you failed 1 test of 30.
t/controller/device.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/30 subtests 
... (etc) ...
```

**Comment by gmambro** [comment]
Were you testing the latest git version?

**Comment by eserte** [comment]
It does not look like it's related to the git version. Currently at the top of http://matrix.cpantesters.org/?dist=App-Manoc%202.99.2-TRIAL;reports=1#sl=7,1 there are two reports generated from the same system (fedora 28), but one is a PASS http://www.cpantesters.org/cpan/report/b78d7900-f809-11e8-a865-a55fcf9fa1a9 and the other is a FAIL http://www.cpantesters.org/cpan/report/cd5e641e-f8c8-11e8-9e43-f1c274115b0b

**Comment by eserte** [comment]
> Were you testing the latest git version?

Sorry, I misunderstood. This was the TRIAL release from CPAN which I tested.

**Comment by gmambro** [comment]
I wasn't able to reproduce the failure, however comparing the builds that pass with the others it looks like all the failures are related to form handling and HTML::FormHandler is older on the system where it fails. I am going to release a new dist with higher requirements based to check if this is a good guess.

**Comment by eserte** [comment]
Statistical analysis suggests that it's something different: http://analysis.cpantesters.org/solved?distv=App-Manoc-2.99.3-TRIAL#env%3ALC_ALL
So this means: it fails if a German locale is set.

**Comment by eserte** [comment]
I checked also with other locales:
* ru_RU.utf8 → fail
* fr_FR.utf8 → pass

(tried these on various Debian systems)

**Comment by gmambro** [comment]
This makes sense: the tests which fail expect the form to give an error when invalid input is provided and this is done by looking for the English error string. HTML::FormHandler supports some localization based on LC_ALL. I was able to reproduce it locally running   LC_ALL=de_DE.UTF-8 prove -l lib/  t/controller/device.t

My tests (including Travis) run with LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

**Comment by gmambro** [comment]
@eserte thank you for pointing out the statistical analysis tool.. it's great!

**Comment by gmambro** [comment]
looks all green now
